# Generated by Django 2.0.5 on 2019-05-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_piinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piinvoice',
            name='sochi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Số Chỉ: '),
        ),
    ]
