# Generated by Django 2.0.5 on 2019-05-10 10:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190509_1610'),
        ('invoices', '0004_tienmat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TienTho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Số Lượng:')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ghi Chú:')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tienthos', to='invoices.Invoice')),
                ('tientho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tienthos', to='products.ProductOut', verbose_name='Tên Sản Phẩm:')),
            ],
        ),
        migrations.AlterField(
            model_name='piinvoice',
            name='piinvoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piinvoices', to='products.ProductIn', verbose_name='Tên Sản Phẩm:'),
        ),
    ]
