# Generated by Django 2.0.5 on 2019-05-10 16:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190509_1610'),
        ('invoices', '0005_auto_20190510_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sochi', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Số Chỉ:')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ghi Chú:')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poinvoices', to='invoices.Invoice')),
                ('poinvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poinvoices', to='products.CongPo')),
            ],
        ),
    ]
