# Generated by Django 2.0.5 on 2019-05-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_poinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='poinvoice',
            name='tienchi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Số Tiền/Chỉ:'),
        ),
    ]
