# Generated by Django 2.0.5 on 2019-05-10 17:49

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_poinvoice_tienchi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TienMatOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienmato', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Tiền Mặt:')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ghi Chú:')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tienmatos', to='invoices.Invoice')),
            ],
        ),
    ]
