# Generated by Django 2.0.5 on 2019-04-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên Sản Phẩm:')),
                ('sochi', models.FloatField(blank=True, max_length=10, null=True, verbose_name='Số Chỉ: ')),
                ('tienchi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Số Tiền/Chỉ:')),
                ('tuoi', models.FloatField(blank=True, max_length=10, null=True, verbose_name='Số Tuổi(%):')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ghi Chú:')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên Sản Phẩm:')),
                ('congtho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Công Thợ:')),
                ('createdpo', models.DateField(auto_now_add=True)),
                ('updatedpo', models.DateField(auto_now=True)),
            ],
        ),
    ]
