# Generated by Django 2.0.5 on 2019-04-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongPo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên Sản Phẩm:')),
                ('tienchi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Số Tiền/Chỉ:')),
                ('tuoi', models.FloatField(blank=True, max_length=10, null=True, verbose_name='Số Tuổi(%):')),
                ('createdco', models.DateField(auto_now_add=True)),
                ('updatedco', models.DateField(auto_now=True)),
            ],
        ),
    ]
