# Generated by Django 2.0.5 on 2019-05-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_congpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congpo',
            name='tuoi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Số Tuổi(%):'),
        ),
        migrations.AlterField(
            model_name='productin',
            name='sochi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Số Chỉ: '),
        ),
        migrations.AlterField(
            model_name='productin',
            name='tuoi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Số Tuổi(%):'),
        ),
    ]
